### ISSUE TITLE
Typescript ES6 Module Resolution on Windows

### ISSUE THREAD

**Issue by mmacfadden** [rollup/rollup-plugin-typescript#29]
Hello,

Great work on this project!  We are just exploring rollup, specifically in combination with typescript.  We are having a small issue.  I am not sure if it is with Rollup itself or the Typescript plugin.  We have a few developers.  For those on a mac, the project works fine.  On a Windows machine we are getting the following error:

```
events.js:141
     throw er; // Unhandled 'error' event
     ^
Error: Could not resolve ./B from C:\Users\Cameron\source\git\typescript\src\main\ts\C.ts
   at C:\Users\Cameron\source\git\typescript\node_modules\gulp-rollup\node_modules\rollup\dist\rollup.js:7701:37
   at tryCatch (C:\Users\Cameron\source\git\typescript\node_modules\gulp-rollup\node_modules\rollup\dist\rollup.js:337:12)
   at invokeCallback (C:\Users\Cameron\source\git\typescript\node_modules\gulp-rollup\node_modules\rollup\dist\rollup.js:349:13)
   at publish (C:\Users\Cameron\source\git\typescript\node_modules\gulp-rollup\node_modules\rollup\dist\rollup.js:320:7)
   at flush (C:\Users\Cameron\source\git\typescript\node_modules\gulp-rollup\node_modules\rollup\dist\rollup.js:131:5)
   at nextTickCallbackWith0Args (node.js:419:9)
```

We are using gulp.  Here is the gulpfile:

``` JavaScript
var gulp = require('gulp');

var del = require('del');
var rename = require('gulp-rename');

var rollup = require('gulp-rollup');
var rollupTypescript = require('rollup-plugin-typescript');

var sourcemaps = require('gulp-sourcemaps');
var uglify = require('gulp-uglify');


gulp.task('build', function () {
  return gulp.src('src/main/ts/C.ts', {read: false})
    .pipe(rollup({
      format: 'iife',
      moduleName: 'libraryname',
      sourceMap: true,
      plugins: [
        rollupTypescript()
      ]
    }))
    .pipe(rename("rollup-test.js"))
    .pipe(sourcemaps.write("."))
    .pipe(gulp.dest("build"));
});

gulp.task('dist', ["build"], function () {
  return gulp.src('build/*.js')
    .pipe(uglify())
    .pipe(rename({
      extname: '.min.js'
    }))
    .pipe(gulp.dest('dist'));
});

gulp.task('clean', function (cb) {
  return del(["build", "dist"], cb);
});

gulp.task('default', ["build"]);
```

and the tsconfig.json:

``` JSON
{
  "compilerOptions": {
    "target": "es6",
    "module": "es6",
    "preserveConstEnums": true,
    "sourceMap": true,
    "declaration": true,
    "listFiles": true
  },
  "exclude": [
    "node_modules",
    "build",
    "dist"
  ]
}
```

and the pacakge.json

``` JSON
{
  "name": "typescript-test",
  "version": "1.0.0",
  "description": "typescript test",
  "tags": [
    "typescript",
    "es6"
  ],
  "author": "",
  "homepage": "",
  "repository": {
    "type": "",
    "url": ""
  },
  "bugs": "",
  "scripts": {
    "build": "gulp"
  },
  "dependencies": {},
  "devDependencies": {
    "del": "^1.2.0",
    "gulp": "^3.9.0",
    "gulp-rename": "^1.2.2",
    "gulp-rollup": "^1.7.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-uglify": "^1.2.0",
    "rollup-plugin-typescript": "^0.5.0",
    "uglify-js": "^2.4.16"
  }
}
```

Here are the three classes:

src/main/ts/A.ts

``` TypeScript
import BClass from "./B";

export default class AClass {
  constructor(public b: BClass) {
    var foo = new BClass(this);
  }
}
```

src/main/ts/B.ts

``` TypeScript
import AClass from "./A";
export default class BClass {
  constructor(public foo: AClass) {
    console.log(foo.b);
  }
}
```

src/main/ts/C.ts

``` TypeScript
import BClass from "./B";
import AClass from "./A";

export default class CClass extends BClass {
  constructor(public a: AClass) {
    super(a);
    var foo = new AClass(this);
  }
}
```

Again this seems to work fine on Macs but doesn't work on at least two separate windows machines (the only two we have tried).  They both fail with the same error.

**Comment by mmacfadden** [comment]
I can post a complete .zip or .tgz of the complete project if that would be useful.

**Comment by Victorystick** [comment]
I'm afraid I don't have any Windows machine to test this on. @TrySound?

**Comment by TrySound** [comment]
@mmacfadden First of all you don't need to use gulp-rollup. Just use rollup-api directly. The example of usage you can find here https://github.com/TrySound/case/blob/master/gulpfile.js#L22-L46

**Comment by mmacfadden** [comment]
Indeed.  This is what I actually wound up doing.  The problem could be with the Gulp Plugin itself, since it is now working using rollup directly. Thanks for the great work.

**Comment by TrySound** [comment]
@mmacfadden In this case close issue please.

**Comment by mmacfadden** [comment]
It seems that this issue is related to the Gulp Plugin specifically.
