### ISSUE TITLE
Cannot convert undefined or null to object, when pointing to ts file

### ISSUE THREAD

**Issue by quantuminformation** [rollup/rollup-plugin-typescript#77]
This project is throwing this error **Cannot convert undefined or null to object**

The file is definitely there.

<img width="806" alt="screen shot 2016-12-20 at 18 41 10" src="https://cloud.githubusercontent.com/assets/216566/21363309/e9c63f5a-c6e3-11e6-9594-ff28bc5916d4.png">

```Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at Object.<anonymous> (/Users/nikos/WebstormProjects/solar-popup/rollup.config.js:9:23)
    at Module._compile (module.js:570:32)
    at Object.require.extensions..js (/Users/nikos/.nvm/versions/node/v6.9.1/lib/node_modules/rollup/bin/rollup:761:8)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/nikos/.nvm/versions/node/v6.9.1/lib/node_modules/rollup/bin/rollup:768:19
    at process._tickCallback (internal/process/next_tick.js:103:7)```

**Comment by PaulBGD** [comment]
I'm really not sure what to say of this as it doesn't _appear_ to be an issue with this project. If this is still occurring leave a reply and I'll reopen this.
